aggregator:
  ip: 127.0.0.1
  port: 5000
connection:
  info:
    ip: 127.0.0.1
    port: 8085
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    npz_file: examples/data/mnist/random/data_party0.npz
  name: MnistPytorchDataHandler
  path: ibmfl.util.data_handlers.mnist_pytorch_data_handler
local_training:
  name: LocalTrainingHandler
  path: ibmfl.party.training.local_training_handler
model:
  name: PytorchFLModel
  path: ibmfl.model.pytorch_fl_model
  spec:
    loss_criterion: nn.NLLLoss
    model_definition: examples/configs/iter_avg/pytorch/pytorch_sequence.pt
    model_name: pytorch-nn
    optimizer: optim.Adadelta
privacy:
  metrics: true
protocol_handler:
  name: PartyProtocolHandler
  path: ibmfl.party.party_protocol_handler
